import { computed, nextTick, ref, shallowRef } from 'vue';
import type { RouteRecordRaw } from 'vue-router';
import { defineStore } from 'pinia';
import { useBoolean } from '@sa/hooks';
import type { CustomRoute, ElegantConstRoute, LastLevelRouteKey, RouteKey, RouteMap } from '@elegant-router/types';
import { SetupStoreId } from '@/enum';
import { router } from '@/router';
import { createStaticRoutes, getAuthVueRoutes } from '@/router/routes';
import { ROOT_ROUTE } from '@/router/routes/builtin';
import { getRoutePath } from '@/router/elegant/transform';
import { fetchGetPersonalMenu } from '@/service/api/rbac';
import { generatedRoutesObj } from '@/router/elegant/routes';
import { useAuthStore } from '../auth';
import { useTabStore } from '../tab';
import {
	filterAuthRoutesByRoles,
	getBreadcrumbsByRoute,
	getCacheRouteNames,
	getGlobalMenusByAuthRoutes,
	getSelectedMenuKeyPathByKey,
	sortRoutesByOrder,
	transformMenuToSearchMenus,
	updateLocaleOfGlobalMenus
} from './shared';
export const useRouteStore = defineStore(SetupStoreId.Route, () => {
	const authStore = useAuthStore();
	const tabStore = useTabStore();
	const { bool: isInitConstantRoute, setBool: setIsInitConstantRoute } = useBoolean();
	const { bool: isInitAuthRoute, setBool: setIsInitAuthRoute } = useBoolean();

	/**
	 * Auth route mode
	 *
	 * It recommends to use static mode in the development environment, and use dynamic mode in the production
	 * environment, if use static mode in development environment, the auth routes will be auto generated by plugin
	 * "@elegant-router/vue"
	 */
	const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE);

	/** Home route key */
	const routeHome = ref(import.meta.env.VITE_ROUTE_HOME);

	/**
	 * Set route home
	 *
	 * @param routeKey Route key
	 */
	function setRouteHome(routeKey: LastLevelRouteKey) {
		routeHome.value = routeKey;
	}

	/** constant routes */
	const constantRoutes = shallowRef<ElegantConstRoute[]>([]);

	function addConstantRoutes(routes: ElegantConstRoute[]) {
		const constantRoutesMap = new Map<string, ElegantConstRoute>([]);

		routes.forEach(route => {
			constantRoutesMap.set(route.name, route);
		});

		constantRoutes.value = Array.from(constantRoutesMap.values());
	}

	/** auth routes */
	const authRoutes = shallowRef<ElegantConstRoute[]>([]);

	function addAuthRoutes(routes: ElegantConstRoute[]) {
		const authRoutesMap = new Map<string, ElegantConstRoute>([]);
		routes.forEach(route => {
			authRoutesMap.set(route.name, route);
		});

		authRoutes.value = Array.from(authRoutesMap.values());
	}

	const removeRouteFns: (() => void)[] = [];

	/** Global menus */
	const menus = ref<App.Global.Menu[]>([]);
	const searchMenus = computed(() => transformMenuToSearchMenus(menus.value));

	/** Get global menus */
	function getGlobalMenus(routes: ElegantConstRoute[]) {
		menus.value = getGlobalMenusByAuthRoutes(routes);
	}

	/** Update global menus by locale */
	function updateGlobalMenusByLocale() {
		menus.value = updateLocaleOfGlobalMenus(menus.value);
	}

	/** Cache routes */
	const cacheRoutes = ref<RouteKey[]>([]);

	/**
	 * Exclude cache routes
	 *
	 * for reset route cache
	 */
	const excludeCacheRoutes = ref<RouteKey[]>([]);

	/**
	 * Get cache routes
	 *
	 * @param routes Vue routes
	 */
	function getCacheRoutes(routes: RouteRecordRaw[]) {
		cacheRoutes.value = getCacheRouteNames(routes);
	}

	/**
	 * Reset route cache
	 *
	 * @default router.currentRoute.value.name current route name
	 * @param routeKey
	 */
	async function resetRouteCache(routeKey?: RouteKey) {
		const routeName = routeKey || (router.currentRoute.value.name as RouteKey);

		excludeCacheRoutes.value.push(routeName);

		await nextTick();

		excludeCacheRoutes.value = [];
	}

	/** Global breadcrumbs */
	const breadcrumbs = computed(() => getBreadcrumbsByRoute(router.currentRoute.value, menus.value));

	/** Reset store */
	async function resetStore() {
		const routeStore = useRouteStore();

		routeStore.$reset();

		resetVueRoutes();

		// after reset store, need to re-init constant route
		await initConstantRoute();
	}

	/** Reset vue routes */
	function resetVueRoutes() {
		removeRouteFns.forEach(fn => fn());
		removeRouteFns.length = 0;
	}

	/** init constant route */
	async function initConstantRoute() {
		if (isInitConstantRoute.value) return;

		const staticRoute = createStaticRoutes();

		if (authRouteMode.value === 'static') {
			addConstantRoutes(staticRoute.constantRoutes);
		} else {
			const data = [
				{
					name: 'login',
					path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
					component: 'layout.blank$view.login',
					props: true,
					meta: {
						title: 'login',
						i18nKey: 'route.login',
						constant: true,
						hideInMenu: true
					}
				},
				{
					name: '403',
					path: '/403',
					component: 'layout.blank$view.403',
					meta: {
						title: '403',
						i18nKey: 'route.403',
						constant: true,
						hideInMenu: true
					}
				},
				{
					name: '404',
					path: '/404',
					component: 'layout.blank$view.404',
					meta: {
						title: '404',
						i18nKey: 'route.404',
						constant: true,
						hideInMenu: true
					}
				},
				{
					name: '500',
					path: '/500',
					component: 'layout.blank$view.500',
					meta: {
						title: '500',
						i18nKey: 'route.500',
						constant: true,
						hideInMenu: true
					}
				},
				// {
				//   name: 'manage_user-detail-nop',
				//   path: '/manage/user-detail-nop/:id',
				//   component: 'view.manage_user-detail-nop',
				//   meta: {
				//     title: '用户详情',
				//     hideInMenu: true,
				//     icon: '',
				//     activeMenu: 'manage_user-nop'
				//   }
				// }
			];
			addConstantRoutes(data);
		}

		handleConstantAndAuthRoutes();

		setIsInitConstantRoute(true);
	}

	/** Init auth route */
	async function initAuthRoute() {
		if (authRouteMode.value === 'static') {
			initStaticAuthRoute();
		} else {
			await initDynamicAuthRoute();
		}

		tabStore.initHomeTab();
	}

	/** Init static auth route */
	function initStaticAuthRoute() {
		const { authRoutes: staticAuthRoutes } = createStaticRoutes();

		if (authStore.isStaticSuper) {
			addAuthRoutes(staticAuthRoutes);
		} else {
			const filteredAuthRoutes = filterAuthRoutesByRoles(staticAuthRoutes, authStore.userInfo.roles);

			addAuthRoutes(filteredAuthRoutes);
		}

		handleConstantAndAuthRoutes();

		setIsInitAuthRoute(true);
	}

	/** Init dynamic auth route */
	async function initDynamicAuthRoute() {
		let { rows: data } = await fetchGetPersonalMenu();
		data = [
			{
				"id": 56,
				"parent_id": 0,
				"show_name": "数字货币管理",
				"icon": "memory:align-horizontal-center",
				"url": "stock",
				"position": "1",
				"open_link": 0,
				"children": [
					{
						"id": 57,
						"parent_id": 56,
						"show_name": "\u7528\u6237\u5217\u8868",
						"icon": "memory:align-horizontal-center",
						"url": "stock_otc",
						"position": "1",
						"open_link": 0,
						"children": [{
							"id": 68,
							"parent_id": 57,
							"show_name": "\u7528\u6237\u7f16\u8f91",
							"icon": "memory:align-horizontal-center",
							"url": "edit",
							"position": "1",
							"open_link": 0
						},
						{
							"id": 74,
							"parent_id": 57,
							"show_name": "\u7528\u6237\u5217\u8868\u67e5\u770b",
							"icon": "memory:align-horizontal-center",
							"url": "list",
							"position": "1",
							"open_link": 0
						},
						{
							"id": 75,
							"parent_id": 57,
							"show_name": "\u7ed1\u5b9a\u4e1a\u52a1\u5458",
							"icon": "memory:align-horizontal-center",
							"url": "bind_salesman",
							"position": "3",
							"open_link": 0
						}
						]
					},
					{
						"id": 65,
						"parent_id": 56,
						"show_name": "\u7528\u6237\u8be6\u60c5",
						"icon": "memory:align-horizontal-center",
						"url": "stock_ipo",
						"position": "2",
						"open_link": 0,
						"children": [{
							"id": 73,
							"parent_id": 65,
							"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
							"icon": "memory:align-horizontal-center",
							"url": "list",
							"position": "1",
							"open_link": 0
						},
						{
							"id": 71,
							"parent_id": 65,
							"show_name": "\u589e\u52a0\u51cf\u5c11",
							"icon": "memory:align-horizontal-center",
							"url": "setCoin",
							"position": "1",
							"open_link": 0
						}
						]
					},
					{
						"id": 65,
						"parent_id": 56,
						"show_name": "\u7528\u6237\u8be6\u60c5",
						"icon": "memory:align-horizontal-center",
						"url": "stock_market",
						"position": "2",
						"open_link": 0,
						"children": [{
							"id": 73,
							"parent_id": 65,
							"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
							"icon": "memory:align-horizontal-center",
							"url": "list",
							"position": "1",
							"open_link": 0
						},
						{
							"id": 71,
							"parent_id": 65,
							"show_name": "\u589e\u52a0\u51cf\u5c11",
							"icon": "memory:align-horizontal-center",
							"url": "setCoin",
							"position": "1",
							"open_link": 0
						}
						]
					}
				]
			},
			{
				"id": 65,
				"parent_id": 56,
				"show_name": "\u7528\u6237\u8be6\u60c5",
				"icon": "memory:align-horizontal-center",
				"url": "website",
				"position": "2",
				"open_link": 0,
				"children": [{
					"id": 73,
					"parent_id": 65,
					"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
					"icon": "memory:align-horizontal-center",
					"url": "website_banner",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 73,
						"parent_id": 65,
						"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
						"icon": "memory:align-horizontal-center",
						"url": "website_banner",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 71,
					"parent_id": 65,
					"show_name": "\u589e\u52a0\u51cf\u5c11",
					"icon": "memory:align-horizontal-center",
					"url": "website_config-page",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 73,
						"parent_id": 65,
						"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
						"icon": "memory:align-horizontal-center",
						"url": "website_banner",
						"position": "1",
						"open_link": 0
					},]
				}
				]
			},
			{
				"id": 25,
				"parent_id": 0,
				"show_name": "\u7cfb\u7edf\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "manage",
				"position": "10",
				"open_link": 0,
				"children": [{
					"id": 26,
					"parent_id": 25,
					"show_name": "\u7ba1\u7406\u5458\u7ba1\u7406",
					"icon": "",
					"url": "manage_manage",
					"position": "1",
					"open_link": 0
				},
				{
					"id": 27,
					"parent_id": 25,
					"show_name": "\u83dc\u5355\u7ba1\u7406",
					"icon": "",
					"url": "manage_menu",
					"position": "2",
					"open_link": 0
				},
				{
					"id": 28,
					"parent_id": 25,
					"show_name": "\u89d2\u8272\u7ba1\u7406",
					"icon": "",
					"url": "manage_role",
					"position": "3",
					"open_link": 0
				}
				]
			},
			{
				"id": 43,
				"parent_id": 0,
				"show_name": "\u8d44\u91d1\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "user",
				"position": "2",
				"open_link": 0,
				"children": [
					{
						"id": 45,
						"parent_id": 43,
						"show_name": "\u63d0\u73b0\u7ba1\u7406",
						"icon": "memory:align-horizontal-center",
						"url": "user_kyc",
						"position": "1",
						"open_link": 0,
						"children": [{
							"id": 69,
							"parent_id": 45,
							"show_name": "\u63d0\u73b0\u5ba1\u6838",
							"icon": "memory:align-horizontal-center",
							"url": "audit",
							"position": "1",
							"open_link": 0
						},
						{
							"id": 72,
							"parent_id": 45,
							"show_name": "\u63d0\u73b0\u5217\u8868\u67e5\u770b",
							"icon": "memory:align-horizontal-center",
							"url": "list",
							"position": "1",
							"open_link": 0
						}
						]
					},
					{
						"id": 44,
						"parent_id": 43,
						"show_name": "\u5165\u91d1\u7ba1\u7406",
						"icon": "memory:align-horizontal-center",
						"url": "user_user-manage",
						"position": "1",
						"open_link": 0,
						"children": [{
							"id": 69,
							"parent_id": 45,
							"show_name": "\u63d0\u73b0\u5ba1\u6838",
							"icon": "memory:align-horizontal-center",
							"url": "audit",
							"position": "1",
							"open_link": 0
						},]
					}
				]
			},
			{
				"id": 49,
				"parent_id": 0,
				"show_name": "\u73b0\u8d27\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "order",
				"position": "4",
				"open_link": 0,
				"children": [{
					"id": 50,
					"parent_id": 49,
					"show_name": "\u73b0\u8d27\u4ea4\u6613\u5bf9\u5217\u8868",
					"icon": "memory:align-horizontal-center",
					"url": "order_ipo",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 50,
						"parent_id": 49,
						"show_name": "\u73b0\u8d27\u4ea4\u6613\u5bf9\u5217\u8868",
						"icon": "memory:align-horizontal-center",
						"url": "spot_list",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 51,
					"parent_id": 49,
					"show_name": "\u73b0\u8d27\u8ba2\u5355",
					"icon": "memory:align-horizontal-center",
					"url": "order_futures",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 50,
						"parent_id": 49,
						"show_name": "\u73b0\u8d27\u4ea4\u6613\u5bf9\u5217\u8868",
						"icon": "memory:align-horizontal-center",
						"url": "spot_list",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 51,
					"parent_id": 49,
					"show_name": "\u73b0\u8d27\u8ba2\u5355",
					"icon": "memory:align-horizontal-center",
					"url": "order_otc",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 50,
						"parent_id": 49,
						"show_name": "\u73b0\u8d27\u4ea4\u6613\u5bf9\u5217\u8868",
						"icon": "memory:align-horizontal-center",
						"url": "spot_list",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 51,
					"parent_id": 49,
					"show_name": "\u73b0\u8d27\u8ba2\u5355",
					"icon": "memory:align-horizontal-center",
					"url": "order_spot",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 50,
						"parent_id": 49,
						"show_name": "\u73b0\u8d27\u4ea4\u6613\u5bf9\u5217\u8868",
						"icon": "memory:align-horizontal-center",
						"url": "spot_list",
						"position": "1",
						"open_link": 0
					},]
				}
				]
			},
			{
				"id": 36,
				"parent_id": 0,
				"show_name": "\u5408\u7ea6\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "crypto",
				"position": "5",
				"open_link": 0,
				"children": [{
					"id": 37,
					"parent_id": 36,
					"show_name": "",
					"icon": null,
					"url": "crypto_symbol",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 37,
						"parent_id": 36,
						"show_name": "",
						"icon": null,
						"url": "derivative_list",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 38,
					"parent_id": 36,
					"show_name": "\u5408\u7ea6\u8ba2\u5355",
					"icon": null,
					"url": "crypto_spot",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 37,
						"parent_id": 36,
						"show_name": "\u5408\u7ea6\u4ea4\u6613\u5bf9\u5217\u8868",
						"icon": null,
						"url": "derivative_list",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 38,
					"parent_id": 36,
					"show_name": "\u5408\u7ea6\u8ba2\u5355",
					"icon": null,
					"url": "crypto_futures",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 37,
						"parent_id": 36,
						"show_name": "\u5408\u7ea6\u4ea4\u6613\u5bf9\u5217\u8868",
						"icon": null,
						"url": "derivative_list",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 38,
					"parent_id": 36,
					"show_name": "\u5408\u7ea6\u8ba2\u5355",
					"icon": null,
					"url": "crypto_coin",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 37,
						"parent_id": 36,
						"show_name": "\u5408\u7ea6\u4ea4\u6613\u5bf9\u5217\u8868",
						"icon": null,
						"url": "derivative_list",
						"position": "1",
						"open_link": 0
					},]
				}
				]
			},
			{
				"id": 31,
				"parent_id": 0,
				"show_name": "\u914d\u7f6e\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "recharge",
				"position": "6",
				"open_link": 0,
				"children": [{
					"id": 32,
					"parent_id": 31,
					"show_name": "\u534f\u8bae\u7ba1\u7406",
					"icon": "",
					"url": "recharge_stock",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 32,
						"parent_id": 31,
						"show_name": "\u534f\u8bae\u7ba1\u7406",
						"icon": "",
						"url": "recharge_stock",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 79,
					"parent_id": 31,
					"show_name": "\u5f39\u7a97\u516c\u544a",
					"icon": "memory:align-horizontal-center",
					"url": "config_announcement",
					"position": "1",
					"open_link": 0
				},
				{
					"id": 33,
					"parent_id": 31,
					"show_name": "Banner\u7ba1\u7406",
					"icon": "",
					"url": "config_banner",
					"position": "1",
					"open_link": 0
				},
				{
					"id": 34,
					"parent_id": 31,
					"show_name": "\u6d88\u606f\u7ba1\u7406",
					"icon": "",
					"url": "config_notice",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 67,
						"parent_id": 34,
						"show_name": "\u6d88\u606f\u7f16\u8f91",
						"icon": "memory:align-horizontal-center",
						"url": "edit",
						"position": "1",
						"open_link": 0
					},
					{
						"id": 66,
						"parent_id": 34,
						"show_name": "\u6d88\u606f\u65b0\u589e",
						"icon": "memory:align-horizontal-center",
						"url": "add",
						"position": "1",
						"open_link": 0
					}
					]
				}
				]
			},
			{
				"id": 76,
				"parent_id": 0,
				"show_name": "OTC",
				"icon": "memory:align-horizontal-center",
				"url": "otc",
				"position": "6",
				"open_link": 0,
				"children": [{
					"id": 77,
					"parent_id": 76,
					"show_name": "OTC\u5217\u8868",
					"icon": "memory:align-horizontal-center",
					"url": "otc_list",
					"position": "1",
					"open_link": 0
				},
				{
					"id": 78,
					"parent_id": 76,
					"show_name": "OTC\u8ba2\u5355",
					"icon": "memory:align-horizontal-center",
					"url": "otc_order",
					"position": "2",
					"open_link": 0
				}
				]
			},
			{
				"id": 62,
				"parent_id": 0,
				"show_name": "\u8d28\u62bc\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "defn",
				"position": "6",
				"open_link": 0,
				"children": [{
					"id": 63,
					"parent_id": 62,
					"show_name": "\u8d28\u62bc\u914d\u7f6e",
					"icon": "memory:align-horizontal-center",
					"url": "defn_pledge",
					"position": "1",
					"open_link": 0
				},
				{
					"id": 64,
					"parent_id": 62,
					"show_name": "\u8d28\u62bc\u8ba2\u5355",
					"icon": "memory:align-horizontal-center",
					"url": "defn_order",
					"position": "2",
					"open_link": 0
				}
				]
			},
			{
				"id": 39,
				"parent_id": 0,
				"show_name": "IEO",
				"icon": "memory:align-horizontal-center",
				"url": "ieo",
				"position": "7",
				"open_link": 0,
				"children": [{
					"id": 41,
					"parent_id": 39,
					"show_name": "IEO\u8ba2\u5355",
					"icon": "memory:align-horizontal-center",
					"url": "ieo_order",
					"position": "1",
					"open_link": 0
				},
				{
					"id": 40,
					"parent_id": 39,
					"show_name": "IEO\u5217\u8868",
					"icon": "memory:align-horizontal-center",
					"url": "ieo_list",
					"position": "5",
					"open_link": 0
				}
				]
			},
			{
				"id": 42,
				"parent_id": 0,
				"show_name": "\u5bfc\u5e08\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "mentor",
				"position": "8",
				"open_link": 0
			},
			{
				"id": 35,
				"parent_id": 0,
				"show_name": "\u64cd\u76d8\u7ba1\u7406",
				"icon": null,
				"url": "control",
				"position": "9",
				"open_link": 0
			},
			{
				"id": 59,
				"parent_id": 0,
				"show_name": "\u7406\u8d22\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "financial",
				"position": "9",
				"open_link": 0,
				"children": [{
					"id": 61,
					"parent_id": 59,
					"show_name": "\u7406\u8d22\u4ea7\u54c1",
					"icon": "memory:align-horizontal-center",
					"url": "financial_product",
					"position": "1",
					"open_link": 0
				},
				{
					"id": 60,
					"parent_id": 59,
					"show_name": "\u7406\u8d22\u8ba2\u5355",
					"icon": "memory:align-horizontal-center",
					"url": "financial_order",
					"position": "2",
					"open_link": 0
				}
				]
			},
			{
				"id": 43,
				"parent_id": 0,
				"show_name": "\u8d44\u91d1\u7ba1\u7406",
				"icon": "memory:align-horizontal-center",
				"url": "order",
				"position": "2",
				"open_link": 0,
				"children": [{
					"id": 49,
					"parent_id": 0,
					"show_name": "\u8d44\u91d1\u7ba1\u7406",
					"icon": "memory:align-horizontal-center",
					"url": "order_futures",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 61,
						"parent_id": 59,
						"show_name": "\u7406\u8d22\u4ea7\u54c1",
						"icon": "memory:align-horizontal-center",
						"url": "financial_product",
						"position": "1",
						"open_link": 0
					},
					{
						"id": 60,
						"parent_id": 59,
						"show_name": "\u7406\u8d22\u8ba2\u5355",
						"icon": "memory:align-horizontal-center",
						"url": "financial_order",
						"position": "2",
						"open_link": 0
					}
					]
				}, {
					"id": 111,
					"parent_id": 0,
					"show_name": "\u8d44\u91d1\u7ba1\u7406",
					"icon": "memory:align-horizontal-center",
					"url": "order_spot",
					"position": "2",
					"open_link": 0,
					"children": [{
						"id": 61,
						"parent_id": 59,
						"show_name": "\u7406\u8d22\u4ea7\u54c1",
						"icon": "memory:align-horizontal-center",
						"url": "financial_product",
						"position": "1",
						"open_link": 0
					},
					{
						"id": 60,
						"parent_id": 59,
						"show_name": "\u7406\u8d22\u8ba2\u5355",
						"icon": "memory:align-horizontal-center",
						"url": "financial_order",
						"position": "2",
						"open_link": 0
					}
					]
				}, {
					"id": 112,
					"parent_id": 0,
					"show_name": "\u8d44\u91d1\u7ba1\u7406",
					"icon": "memory:align-horizontal-center",
					"url": "order_ipo",
					"position": "2",
					"open_link": 0,
				}, {
					"id": 113,
					"parent_id": 0,
					"show_name": "\u8d44\u91d1\u7ba1\u7406",
					"icon": "memory:align-horizontal-center",
					"url": "order_otc",
					"position": "2",
					"open_link": 0,
				},]

			},
			{
				"id": 1165,
				"parent_id": 56,
				"show_name": "\u7528\u6237\u8be6\u60c5",
				"icon": "memory:align-horizontal-center",
				"url": "data-detail",
				"position": "2",
				"open_link": 0,
				"children": [{
					"id": 73,
					"parent_id": 65,
					"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
					"icon": "memory:align-horizontal-center",
					"url": "",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 73,
						"parent_id": 65,
						"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
						"icon": "memory:align-horizontal-center",
						"url": "website_banner",
						"position": "1",
						"open_link": 0
					},]
				},]
			},
			{
				"id": 165,
				"parent_id": 56,
				"show_name": "\u7528\u6237\u8be6\u60c5",
				"icon": "memory:align-horizontal-center",
				"url": "flow",
				"position": "2",
				"open_link": 0,
				"children": [{
					"id": 73,
					"parent_id": 65,
					"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
					"icon": "memory:align-horizontal-center",
					"url": "flow_stock",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 73,
						"parent_id": 65,
						"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
						"icon": "memory:align-horizontal-center",
						"url": "website_banner",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 71,
					"parent_id": 65,
					"show_name": "\u589e\u52a0\u51cf\u5c11",
					"icon": "memory:align-horizontal-center",
					"url": "flow_spot",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 73,
						"parent_id": 65,
						"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
						"icon": "memory:align-horizontal-center",
						"url": "website_banner",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 71,
					"parent_id": 65,
					"show_name": "\u589e\u52a0\u51cf\u5c11",
					"icon": "memory:align-horizontal-center",
					"url": "flow_futures",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 73,
						"parent_id": 65,
						"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
						"icon": "memory:align-horizontal-center",
						"url": "website_banner",
						"position": "1",
						"open_link": 0
					},]
				},
				{
					"id": 71,
					"parent_id": 65,
					"show_name": "\u589e\u52a0\u51cf\u5c11",
					"icon": "memory:align-horizontal-center",
					"url": "flow_futures",
					"position": "1",
					"open_link": 0,
					"children": [{
						"id": 73,
						"parent_id": 65,
						"show_name": "\u7528\u6237\u8be6\u60c5\u67e5\u770b",
						"icon": "memory:align-horizontal-center",
						"url": "website_banner",
						"position": "1",
						"open_link": 0
					},]
				}
				]
			},
		]
		console.log(data)
		authStore.setMenuRootMap(data);
		const ids = [];
		const routes = [];
		// data遍历，当url和generatedRoutesObj的key相同时，则加入generatedRoutesObj的value值， data中的数据有children时，children替换为generatedRoutesObj的value值
		data.forEach(item => {
			if (ids.includes(item.id)) {
				return;
			}
			ids.push(item.id);
			const route = generatedRoutesObj[item.url];
			if (item.url && generatedRoutesObj[item.url]) {
				routes.push(route);
				if (item.children) {
					route.children = item.children
						.map(child => {
							return generatedRoutesObj[child.url];
						})
						.filter(Boolean);
				}
			}
		});
		try {
			if (routes.length === 0) {
				authStore.resetStore();
				return;
			}
			const home = routes[0].name;
			addAuthRoutes(routes);

			handleConstantAndAuthRoutes();

			setRouteHome(home);

			handleUpdateRootRouteRedirect(home);

			setIsInitAuthRoute(true);
		} catch (error) {
			console.log(error, 'error');
			// if fetch user routes failed, reset store
			authStore.resetStore();
		}
	}

	/** handle constant and auth routes */
	function handleConstantAndAuthRoutes() {
		const allRoutes = [...constantRoutes.value, ...authRoutes.value];

		const sortRoutes = sortRoutesByOrder(allRoutes);

		const vueRoutes = getAuthVueRoutes(sortRoutes);
		resetVueRoutes();

		addRoutesToVueRouter(vueRoutes);

		getGlobalMenus(sortRoutes);

		getCacheRoutes(vueRoutes);
	}

	/**
	 * Add routes to vue router
	 *
	 * @param routes Vue routes
	 */
	function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
		routes.forEach(route => {
			const removeFn = router.addRoute(route);
			addRemoveRouteFn(removeFn);
		});
	}

	/**
	 * Add remove route fn
	 *
	 * @param fn
	 */
	function addRemoveRouteFn(fn: () => void) {
		removeRouteFns.push(fn);
	}

	/**
	 * Update root route redirect when auth route mode is dynamic
	 *
	 * @param redirectKey Redirect route key
	 */
	function handleUpdateRootRouteRedirect(redirectKey: LastLevelRouteKey) {
		const redirect = getRoutePath(redirectKey);

		if (redirect) {
			const rootRoute: CustomRoute = { ...ROOT_ROUTE, redirect };

			router.removeRoute(rootRoute.name);

			const [rootVueRoute] = getAuthVueRoutes([rootRoute]);

			router.addRoute(rootVueRoute);
		}
	}

	/**
	 * Get selected menu key path
	 *
	 * @param selectedKey Selected menu key
	 */
	function getSelectedMenuKeyPath(selectedKey: string) {
		return getSelectedMenuKeyPathByKey(selectedKey, menus.value);
	}

	async function onRouteSwitchWhenLoggedIn() {
		authStore.initUserInfo();
	}

	async function onRouteSwitchWhenNotLoggedIn() {
		// some global init logic if it does not need to be logged in
	}

	return {
		resetStore,
		routeHome,
		menus,
		searchMenus,
		updateGlobalMenusByLocale,
		cacheRoutes,
		excludeCacheRoutes,
		resetRouteCache,
		breadcrumbs,
		initConstantRoute,
		isInitConstantRoute,
		initAuthRoute,
		isInitAuthRoute,
		setIsInitAuthRoute,
		getSelectedMenuKeyPath,
		onRouteSwitchWhenLoggedIn,
		onRouteSwitchWhenNotLoggedIn
	};
});
