/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  crypto_coin: () => import("@/views/crypto/coin/index.vue"),
  crypto_futures: () => import("@/views/crypto/futures/index.vue"),
  crypto_spot: () => import("@/views/crypto/spot/index.vue"),
  crypto_symbol: () => import("@/views/crypto/symbol/index.vue"),
  etf_config: () => import("@/views/etf/config/index.vue"),
  etf_product: () => import("@/views/etf/product/index.vue"),
  flow_futures: () => import("@/views/flow/futures/index.vue"),
  flow_loan: () => import("@/views/flow/loan/index.vue"),
  flow_spot: () => import("@/views/flow/spot/index.vue"),
  flow_stock: () => import("@/views/flow/stock/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_manage: () => import("@/views/manage/manage/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  order_despoit: () => import("@/views/order/despoit/index.vue"),
  order_etf: () => import("@/views/order/etf/index.vue"),
  order_futures: () => import("@/views/order/futures/index.vue"),
  order_ipo: () => import("@/views/order/ipo/index.vue"),
  order_otc: () => import("@/views/order/otc/index.vue"),
  "order_spot-despoit": () => import("@/views/order/spot-despoit/index.vue"),
  "order_spot-withdraw": () => import("@/views/order/spot-withdraw/index.vue"),
  order_spot: () => import("@/views/order/spot/index.vue"),
  "order_stock-withdraw": () => import("@/views/order/stock-withdraw/index.vue"),
  order_tagesstrategie: () => import("@/views/order/tagesstrategie/index.vue"),
  stock_ipo: () => import("@/views/stock/ipo/index.vue"),
  stock_market: () => import("@/views/stock/market/index.vue"),
  stock_otc: () => import("@/views/stock/otc/index.vue"),
  user_kyc: () => import("@/views/user/kyc/index.vue"),
  user_level: () => import("@/views/user/level/index.vue"),
  "user_user-manage": () => import("@/views/user/user-manage/index.vue"),
  wallet_futures: () => import("@/views/wallet/futures/index.vue"),
  wallet_loan: () => import("@/views/wallet/loan/index.vue"),
  wallet_spot: () => import("@/views/wallet/spot/index.vue"),
  wallet_stock: () => import("@/views/wallet/stock/index.vue"),
  website_banner: () => import("@/views/website/banner/index.vue"),
  "website_config-page": () => import("@/views/website/config-page/index.vue"),
  website_platform: () => import("@/views/website/platform/index.vue"),
};
