/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  crypto_coin: () => import("@/views/crypto/coin/index.vue"),
  crypto_futures: () => import("@/views/crypto/futures/index.vue"),
  crypto_spot: () => import("@/views/crypto/spot/index.vue"),
  crypto_symbol: () => import("@/views/crypto/symbol/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_manage: () => import("@/views/manage/manage/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  order_futures: () => import("@/views/order/futures/index.vue"),
  order_ipo: () => import("@/views/order/ipo/index.vue"),
  order_otc: () => import("@/views/order/otc/index.vue"),
  order_spot: () => import("@/views/order/spot/index.vue"),
  recharge_stock: () => import("@/views/recharge/stock/index.vue"),
  stock_ipo: () => import("@/views/stock/ipo/index.vue"),
  stock_market: () => import("@/views/stock/market/index.vue"),
  stock_otc: () => import("@/views/stock/otc/index.vue"),
  user_kyc: () => import("@/views/user/kyc/index.vue"),
  "user_user-manage": () => import("@/views/user/user-manage/index.vue"),
};
