/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'crypto',
    path: '/crypto',
    component: 'layout.base',
    meta: {
      title: '数字货币管理',
      icon: 'ic:baseline-currency-bitcoin'
    },
    children: [
      {
        name: 'crypto_coin',
        path: '/crypto/coin',
        component: 'view.crypto_coin',
        meta: {
          title: '币种管理',
          icon: 'ic:baseline-monetization-on'
        }
      },
      {
        name: 'crypto_futures',
        path: '/crypto/futures',
        component: 'view.crypto_futures',
        meta: {
          title: '合约管理',
          icon: 'ic:baseline-assignment'
        }
      },
      {
        name: 'crypto_spot',
        path: '/crypto/spot',
        component: 'view.crypto_spot',
        meta: {
          title: '现货管理',
          icon: 'ic:baseline-shopping-cart'
        }
      },
      {
        name: 'crypto_symbol',
        path: '/crypto/symbol',
        component: 'view.crypto_symbol',
        meta: {
          title: 'Symnol管理',
          icon: 'ic:baseline-label'
        }
      }
    ]
  },
  {
    name: 'data-detail',
    path: '/data-detail',
    component: 'layout.base$view.data-detail',
    meta: {
      title: 'data-detail',
      icon: 'ic:baseline-analytics'
    }
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base$view.demo',
    meta: {
      title: 'demo',
      icon: 'ic:baseline-science'
    }
  },
  {
    name: 'flow',
    path: '/flow',
    component: 'layout.base',
    meta: {
      title: '钱包管理',
      icon: 'ic:baseline-account-balance-wallet'
    },
    children: [
      {
        name: 'flow_futures',
        path: '/flow/futures',
        component: 'view.flow_futures',
        meta: {
          title: '合约钱包流水'
        }
      },
      {
        name: 'flow_loan',
        path: '/flow/loan',
        component: 'view.flow_loan',
        meta: {
          title: '贷款钱包流水'
        }
      },
      {
        name: 'flow_spot',
        path: '/flow/spot',
        component: 'view.flow_spot',
        meta: {
          title: '现货钱包流水'
        }
      },
      {
        name: 'flow_stock',
        path: '/flow/stock',
        component: 'view.flow_stock',
        meta: {
          title: '股票钱包流水'
        }
      },
      {
        name: 'flow_wallet-futures',
        path: '/flow/wallet-futures',
        component: 'view.flow_wallet-futures',
        meta: {
          title: '合约钱包'
        }
      },
      {
        name: 'flow_wallet-loan',
        path: '/flow/wallet-loan',
        component: 'view.flow_wallet-loan',
        meta: {
          title: '贷款钱包'
        }
      },
      {
        name: 'flow_wallet-spot',
        path: '/flow/wallet-spot',
        component: 'view.flow_wallet-spot',
        meta: {
          title: '现货钱包'
        }
      },
      {
        name: 'flow_wallet-stock',
        path: '/flow/wallet-stock',
        component: 'view.flow_wallet-stock',
        meta: {
          title: '股票钱包'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: '系统管理',
      icon: 'ic:baseline-settings'
    },
    children: [
      {
        name: 'manage_manage',
        path: '/manage/manage',
        component: 'view.manage_manage',
        meta: {
          title: '管理员管理',
          icon: 'ic:baseline-admin-panel-settings'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: '菜单管理',
          icon: 'ic:baseline-menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: '角色管理',
          icon: 'ic:baseline-security'
        }
      }
    ]
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base',
    meta: {
      title: '订单',
      icon: 'ic:baseline-receipt'
    },
    children: [
      {
        name: 'order_futures',
        path: '/order/futures',
        component: 'view.order_futures',
        meta: {
          title: '合约订单',
          icon: 'ic:baseline-assignment-turned-in'
        }
      },
      {
        name: 'order_ipo',
        path: '/order/ipo',
        component: 'view.order_ipo',
        meta: {
          title: 'IPO订单',
          icon: 'ic:baseline-public'
        }
      },
      {
        name: 'order_otc',
        path: '/order/otc',
        component: 'view.order_otc',
        meta: {
          title: '大宗订单',
          icon: 'ic:baseline-business'
        }
      },
      {
        name: 'order_spot',
        path: '/order/spot',
        component: 'view.order_spot',
        meta: {
          title: '现货订单',
          icon: 'ic:baseline-local-offer'
        }
      }
    ]
  },
  {
    name: 'recharge',
    path: '/recharge',
    component: 'layout.base',
    meta: {
      title: 'recharge',
      icon: 'ic:baseline-battery-charging-full'
    },
    children: [
      {
        name: 'recharge_stock',
        path: '/recharge/stock',
        component: 'view.recharge_stock',
        meta: {
          title: 'recharge_stock',
          icon: 'ic:baseline-add-circle'
        }
      }
    ]
  },
  {
    name: 'stock',
    path: '/stock',
    component: 'layout.base',
    meta: {
      title: '股票管理',
      icon: 'ic:baseline-trending-up'
    },
    children: [
      {
        name: 'stock_ipo',
        path: '/stock/ipo',
        component: 'view.stock_ipo',
        meta: {
          title: 'IPO股票',
          icon: 'ic:baseline-new-releases'
        }
      },
      {
        name: 'stock_market',
        path: '/stock/market',
        component: 'view.stock_market',
        meta: {
          title: '市场股票',
          icon: 'ic:baseline-store'
        }
      },
      {
        name: 'stock_otc',
        path: '/stock/otc',
        component: 'view.stock_otc',
        meta: {
          title: '大宗股票',
          icon: 'ic:baseline-account-balance'
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: '用户管理',
      icon: 'ic:baseline-people'
    },
    children: [
      {
        name: 'user_kyc',
        path: '/user/kyc',
        component: 'view.user_kyc',
        meta: {
          title: 'KYC管理',
          icon: 'ic:baseline-verified-user'
        }
      },
      {
        name: 'user_user-manage',
        path: '/user/user-manage',
        component: 'view.user_user-manage',
        meta: {
          title: '用户列表',
          icon: 'ic:baseline-person'
        }
      }
    ]
  },
  {
    name: 'website',
    path: '/website',
    component: 'layout.base',
    meta: {
      title: '网站管理',
      icon: 'ic:baseline-web'
    },
    children: [
      {
        name: 'website_banner',
        path: '/website/banner',
        component: 'view.website_banner',
        meta: {
          title: 'banner',
          icon: 'ic:baseline-image'
        }
      },
      {
        name: 'website_config-page',
        path: '/website/config-page',
        component: 'view.website_config-page',
        meta: {
          title: '配置管理',
          icon: 'ic:baseline-tune'
        }
      }
    ]
  }
];

// 返回generatedRoutes，name为key，对象为value的对象, 子集也需要拍平
export const generatedRoutesObj = generatedRoutes.reduce((acc: any, route) => {
  acc[route.name] = route;
  if ('children' in route && route.children) {
    route.children.forEach((child: any) => {
      acc[child.name] = child;
    });
    // 删除children
    // Reflect.deleteProperty(route, 'children');
  }
  return acc;
}, {});
