/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'crypto',
    path: '/crypto',
    component: 'layout.base',
    meta: {
      title: '数字货币管理',
      icon: 'mdi:currency-btc'
    },
    children: [
      {
        name: 'crypto_coin',
        path: '/crypto/coin',
        component: 'view.crypto_coin',
        meta: {
          title: '币种管理',
          icon: 'mdi:coin'
        }
      },
      {
        name: 'crypto_futures',
        path: '/crypto/futures',
        component: 'view.crypto_futures',
        meta: {
          title: '合约管理',
          icon: 'mdi:file-document-edit'
        }
      },
      {
        name: 'crypto_spot',
        path: '/crypto/spot',
        component: 'view.crypto_spot',
        meta: {
          title: '现货管理',
          icon: 'mdi:shopping'
        }
      },
      {
        name: 'crypto_symbol',
        path: '/crypto/symbol',
        component: 'view.crypto_symbol',
        meta: {
          title: '交易对管理',
          icon: 'mdi:currency-usd'
        }
      }
    ]
  },
  {
    name: 'etf',
    path: '/etf',
    component: 'layout.base',
    meta: {
      title: 'AI管理',
      icon: 'mdi:trending-up'
    },
    children: [
      {
        name: 'etf_config',
        path: '/etf/config',
        component: 'view.etf_config',
        meta: {
          title: 'AI配置',
          icon: 'mdi:tune'
        }
      },
      {
        name: 'etf_product',
        path: '/etf/product',
        component: 'view.etf_product',
        meta: {
          title: 'AI产品',
          icon: 'mdi:package-variant'
        }
      }
    ]
  },
  {
    name: 'financial',
    path: '/financial',
    component: 'layout.base',
    meta: {
      title: '日内管理',
      icon: 'mdi:finance'
    },
    children: [
      {
        name: 'financial_order',
        path: '/financial/order',
        component: 'view.financial_order',
        meta: {
          title: '日内订单',
          icon: 'mdi:receipt'
        }
      },
      {
        name: 'financial_product',
        path: '/financial/product',
        component: 'view.financial_product',
        meta: {
          title: '日内产品',
          icon: 'mdi:package-variant-closed'
        }
      }
    ]
  },
  {
    name: 'flow',
    path: '/flow',
    component: 'layout.base',
    meta: {
      title: '钱包流水管理',
      icon: 'mdi:bank-transfer'
    },
    children: [
      {
        name: 'flow_futures',
        path: '/flow/futures',
        component: 'view.flow_futures',
        meta: {
          title: '合约钱包流水',
          icon: 'mdi:chart-line'
        }
      },
      {
        name: 'flow_loan',
        path: '/flow/loan',
        component: 'view.flow_loan',
        meta: {
          title: '贷款钱包流水',
          icon: 'mdi:handshake'
        }
      },
      {
        name: 'flow_spot',
        path: '/flow/spot',
        component: 'view.flow_spot',
        meta: {
          title: '现货钱包流水',
          icon: 'mdi:cash-multiple'
        }
      },
      {
        name: 'flow_stock',
        path: '/flow/stock',
        component: 'view.flow_stock',
        meta: {
          title: '股票钱包流水',
          icon: 'mdi:trending-up'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: '系统管理',
      icon: 'mdi:cog'
    },
    children: [
      {
        name: 'manage_manage',
        path: '/manage/manage',
        component: 'view.manage_manage',
        meta: {
          title: '管理员管理',
          icon: 'mdi:account-cog'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: '菜单管理',
          icon: 'mdi:menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: '角色管理',
          icon: 'mdi:shield-account'
        }
      }
    ]
  },
  {
    name: 'money',
    path: '/money',
    component: 'layout.base',
    meta: {
      title: '出入金管理',
      icon: 'mdi:bank-transfer'
    },
    children: [
      {
        name: 'money_despoit',
        path: '/money/despoit',
        component: 'view.money_despoit',
        meta: {
          title: '股票充值订单',
          icon: 'mdi:cash-plus'
        }
      },
      {
        name: 'money_spot-despoit',
        path: '/money/spot-despoit',
        component: 'view.money_spot-despoit',
        meta: {
          title: '现货充值订单',
          icon: 'mdi:bitcoin'
        }
      },
      {
        name: 'money_spot-withdraw',
        path: '/money/spot-withdraw',
        component: 'view.money_spot-withdraw',
        meta: {
          title: '现货提现订单',
          icon: 'mdi:cash-minus'
        }
      },
      {
        name: 'money_stock-withdraw',
        path: '/money/stock-withdraw',
        component: 'view.money_stock-withdraw',
        meta: {
          title: '股票提现订单',
          icon: 'mdi:bank-transfer-out'
        }
      }
    ]
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base',
    meta: {
      title: '订单管理',
      icon: 'mdi:clipboard-list'
    },
    children: [
      {
        name: 'order_etf',
        path: '/order/etf',
        component: 'view.order_etf',
        meta: {
          title: 'ETF订单',
          icon: 'mdi:clipboard-text'
        }
      },
      {
        name: 'order_futures',
        path: '/order/futures',
        component: 'view.order_futures',
        meta: {
          title: '合约订单',
          icon: 'mdi:file-chart'
        }
      },
      {
        name: 'order_ipo',
        path: '/order/ipo',
        component: 'view.order_ipo',
        meta: {
          title: 'IPO订单',
          icon: 'mdi:rocket-launch'
        }
      },
      {
        name: 'order_loan',
        path: '/order/loan',
        component: 'view.order_loan',
        meta: {
          title: '贷款订单',
          icon: 'mdi:candy'
        }
      },
      {
        name: 'order_otc',
        path: '/order/otc',
        component: 'view.order_otc',
        meta: {
          title: '大宗订单',
          icon: 'mdi:briefcase'
        }
      },
      {
        name: 'order_spot',
        path: '/order/spot',
        component: 'view.order_spot',
        meta: {
          title: '现货订单',
          icon: 'mdi:tag'
        }
      },
      {
        name: 'order_stock',
        path: '/order/stock',
        component: 'view.order_stock',
        meta: {
          title: '股票订单',
          icon: 'mdi:clipboard-text'
        }
      },
      {
        name: 'order_tagesstrategie',
        path: '/order/tagesstrategie',
        component: 'view.order_tagesstrategie',
        meta: {
          title: '日内策略订单',
          icon: 'mdi:chart-timeline-variant'
        }
      }
    ]
  },
  {
    name: 'stock',
    path: '/stock',
    component: 'layout.base',
    meta: {
      title: '股票管理',
      icon: 'mdi:chart-line'
    },
    children: [
      {
        name: 'stock_ipo',
        path: '/stock/ipo',
        component: 'view.stock_ipo',
        meta: {
          title: 'IPO股票',
          icon: 'mdi:rocket'
        }
      },
      {
        name: 'stock_market',
        path: '/stock/market',
        component: 'view.stock_market',
        meta: {
          title: '市场股票',
          icon: 'mdi:store'
        }
      },
      {
        name: 'stock_otc',
        path: '/stock/otc',
        component: 'view.stock_otc',
        meta: {
          title: '大宗股票',
          icon: 'mdi:bank'
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: '用户管理',
      icon: 'mdi:account-group'
    },
    children: [
      {
        name: 'user_kyc',
        path: '/user/kyc',
        component: 'view.user_kyc',
        meta: {
          title: 'KYC管理',
          icon: 'mdi:card-account-details'
        }
      },
      {
        name: 'user_level',
        path: '/user/level',
        component: 'view.user_level',
        meta: {
          title: '用户等级',
          icon: 'mdi:account-cog'
        }
      },
      {
        name: 'user_user-manage',
        path: '/user/user-manage',
        component: 'view.user_user-manage',
        meta: {
          title: '用户列表',
          icon: 'mdi:account-multiple'
        }
      }
    ]
  },
  {
    name: 'wallet',
    path: '/wallet',
    component: 'layout.base',
    meta: {
      title: '钱包管理',
      icon: 'mdi:wallet'
    },
    children: [
      {
        name: 'wallet_futures',
        path: '/wallet/futures',
        component: 'view.wallet_futures',
        meta: {
          title: '合约钱包',
          icon: 'mdi:chart-timeline-variant'
        }
      },
      {
        name: 'wallet_loan',
        path: '/wallet/loan',
        component: 'view.wallet_loan',
        meta: {
          title: '贷款钱包',
          icon: 'mdi:handshake-outline'
        }
      },
      {
        name: 'wallet_spot',
        path: '/wallet/spot',
        component: 'view.wallet_spot',
        meta: {
          title: '现货钱包',
          icon: 'mdi:cash'
        }
      },
      {
        name: 'wallet_stock',
        path: '/wallet/stock',
        component: 'view.wallet_stock',
        meta: {
          title: '股票钱包',
          icon: 'mdi:chart-areaspline'
        }
      }
    ]
  },
  {
    name: 'website',
    path: '/website',
    component: 'layout.base',
    meta: {
      title: '网站管理',
      icon: 'mdi:web'
    },
    children: [
      {
        name: 'website_announcement',
        path: '/website/announcement',
        component: 'view.website_announcement',
        meta: {
          title: '公告管理'
        }
      },
      {
        name: 'website_banner',
        path: '/website/banner',
        component: 'view.website_banner',
        meta: {
          title: 'Banner管理',
          icon: 'mdi:image'
        }
      },
      {
        name: 'website_config-page',
        path: '/website/config-page',
        component: 'view.website_config-page',
        meta: {
          title: '配置管理',
          icon: 'mdi:tune'
        }
      },
      {
        name: 'website_platform',
        path: '/website/platform',
        component: 'view.website_platform',
        meta: {
          title: '平台设置',
          icon: 'mdi:server'
        }
      }
    ]
  }
];

// 返回generatedRoutes，name为key，对象为value的对象, 子集也需要拍平
export const generatedRoutesObj = generatedRoutes.reduce((acc: any, route) => {
  acc[route.name] = route;
  if ('children' in route && route.children) {
    route.children.forEach((child: any) => {
      acc[child.name] = child;
    });
    // 删除children
    // Reflect.deleteProperty(route, 'children');
  }
  return acc;
}, {});
